//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salary_software
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATA()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int ID_DATA { get; set; }
        public string LastName_person { get; set; }
        public string FirstName_person { get; set; }
        public string MiddleName_person { get; set; }
        public string PassportSeries { get; set; }
        public string NumberPassport { get; set; }
        public int CountChildren { get; set; }
        public System.DateTime Birthday { get; set; }
        public string NumberTelephone { get; set; }
        public int POLID { get; set; }
        public int PositionID { get; set; }
        public int AddressID { get; set; }
    
        public virtual AddressBD AddressBD { get; set; }
        public virtual Pol Pol { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
