//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salary_software
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gr682_gnmEntities : DbContext
    {
        public gr682_gnmEntities()
            : base("name=gr682_gnmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressBD> AddressBD { get; set; }
        public virtual DbSet<DATA> DATA { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Personbd> Personbd { get; set; }
        public virtual DbSet<Pol> Pol { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Reg> Reg { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
        public virtual DbSet<Typestaxes> Typestaxes { get; set; }
    }
}
