//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salary_software
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int ID_Payments { get; set; }
        public decimal NDFL { get; set; }
        public decimal PFR { get; set; }
        public decimal FSS { get; set; }
        public decimal Premiya { get; set; }
        public decimal NaRuki { get; set; }
        public decimal DayRate { get; set; }
        public int CountDay { get; set; }
        public decimal Nachisleno { get; set; }
        public decimal ZPTaxes { get; set; }
        public System.DateTime Date { get; set; }
        public int DATAID { get; set; }
    
        public virtual DATA DATA { get; set; }
    }
}
