//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salary_software
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personbd
    {
        public int ID_Person { get; set; }
        public string LastName_person { get; set; }
        public string FirstName_person { get; set; }
        public string MiddleName_person { get; set; }
        public int IDReg { get; set; }
        public int IDRole { get; set; }
    
        public virtual Reg Reg { get; set; }
        public virtual Role Role { get; set; }
    }
}
