//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salary_software
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        public int ID { get; set; }
        public double Oklad { get; set; }
        public System.DateTime DR { get; set; }
        public System.DateTime DP { get; set; }
        public string Pol { get; set; }
        public int Kolvodet { get; set; }
        public Nullable<int> ID_FIO { get; set; }
    }
}
